import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <header id="ppal">HEADER PRINCIPAL</header>
        <nav className="bg-green-600 text-white pb-8 pt-8 w-full flex justify-center">
          <Link href="/aromaticas">Aromáticas</Link> |
          <Link href="/frutales">Frutales</Link> |
          <Link href="/herbaceas">Herbaceas</Link>
          <Link href="/herramientas">Herramientas</Link>
        </nav>
        {children}
        <footer id="ppal">FOOTER PRINCIPAL</footer>
      </body>
    </html>
  );
}
